version: '3.4'
services:
  gcs-share:
    image: ${docker.share.image}:${alfresco.share.version}
    environment:
      REPO_HOST: gcs-acs
      REPO_PORT: 8080
    ports:
      - "${share.port}:8080"
  gcs-acs:
    image: alfresco-content-services-gcs:development
    build:
      dockerfile: ./Dockerfile
      context: ../../../target
    environment:
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888 -Dgcs.bucketName=***REMOVED*** -Dgcs.keyFileName=***REMOVED***"
    ports:
      - "${acs.port}:8080"
      - "${acs.debug.port}:8888"
    volumes:
      - gcs-acs-volume:/usr/local/tomcat/alf_data
    depends_on:
      - gcs-postgres
  gcs-postgres:
    image: postgres:9.6
    environment:
      POSTGRES_DB: alfresco
      POSTGRES_USER: alfresco
      POSTGRES_PASSWORD: alfresco
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    ports:
      - "${postgres.port}:5432"
    volumes:
      - gcs-db-volume:/var/lib/postgresql/data
  gcs-ass:
    image: alfresco/alfresco-search-services:1.2.0
    environment:
      SOLR_ALFRESCO_HOST: gcs-acs
      SOLR_ALFRESCO_PORT: 8080
      SOLR_SOLR_HOST: gcs-ass
      SOLR_SOLR_PORT: 8983
      SOLR_CREATE_ALFRESCO_DEFAULTS: alfresco,archive
    ports:
      - "8983:8983"
    volumes:
      - gcs-ass-volume:/opt/alfresco-search-services/contentstore
      - gcs-ass-volume:/opt/alfresco-search-services/data
volumes:
  gcs-acs-volume:
    external: true
  gcs-db-volume:
    external: true
  gcs-ass-volume:
    external: true